env:
  global:
    - CC_TEST_REPORTER_ID=a5a5641cce52e23ebf6c335dda5d173abb9bf9858fa7e1428ea31b2bdedda63b
language: node_js
node_js:
  - 6
before_install:
  - npm install grunt-cli -g
install:
  - npm install
  - grunt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - grunt phantomjs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
